name: 'CDash Status'
on:
  push:
  pull_request_target:

jobs:
  cdash-status:
    runs-on: ubuntu-latest
    steps:
      - uses: kitware/cdash-status@v2
        with:
          project: "TOOLS-SDK"
